version: '3.9'

services:
  web:
    build: ../django_app
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../django_app:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: dev_db
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: redis_cache
    ports:
      - "6379:6379"

volumes:
  pgdata:
